/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class CoeficientesView extends javax.swing.JPanel {

    /**
     * Creates new form CoeficientesView
     */
    public CoeficientesView() {
        initComponents();
    }

    public JTabbedPane getJTPane() {
        return JTPane;
    }

    public JTextField getTxtgamaEsforcos() {
        return txtgamaEsforcos;
    }

    public JButton getbtnConfirmargama() {
        return btnConfirmarGama;
    }

    public JButton getBtnConfirmarGamas() {
        return btnConfirmarGamas;
    }

    public JTextField getTxtGamac() {
        return txtgamaC;
    }

    public JTextField getTxtGamaF() {
        return txtgamaF;
    }

    public JButton getBtnOK() {
        return btnOK;
    }

    public JTextField getTxtLambda() {
        return txtLambda;
    }

    public JTextField getTxtalfa() {
        return txtAlfa;
    }

    public JTextField getTxtSigmaCd() {
        return txtSigmaCd;
    }

    public JTextField getTxtFcd() {
        return txtFcd;
    }

    public JTextField getTxtE0() {
        return txtE0;
    }

    public JTextField getTxtEu() {
        return txtEu;
    }

    public JTextField getTxtEuAco() {
        return txtEuAco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JTPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtgamaC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtgamaF = new javax.swing.JTextField();
        btnConfirmarGamas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLambda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAlfa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFcd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSigmaCd = new javax.swing.JTextField();
        txtEuAco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtE0 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEu = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtgamaEsforcos = new javax.swing.JTextField();
        btnConfirmarGama = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("γc: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtgamaC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtgamaC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgamaC.setText("1.4");
        txtgamaC.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(txtgamaC, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("γf: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtgamaF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtgamaF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgamaF.setText("1.15");
        txtgamaF.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(txtgamaF, gridBagConstraints);

        btnConfirmarGamas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnConfirmarGamas.setText("Confirmar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(btnConfirmarGamas, gridBagConstraints);

        JTPane.addTab("Coeficientes de minoração", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("λ: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        txtLambda.setEditable(false);
        txtLambda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtLambda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLambda.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtLambda, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("αc: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        txtAlfa.setEditable(false);
        txtAlfa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtAlfa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlfa.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtAlfa, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("fcd (MPa): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        txtFcd.setEditable(false);
        txtFcd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtFcd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFcd.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtFcd, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("σcd (MPa): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        txtSigmaCd.setEditable(false);
        txtSigmaCd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtSigmaCd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtSigmaCd, gridBagConstraints);

        txtEuAco.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtEuAco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEuAco.setText("10");
        txtEuAco.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtEuAco, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("εuAco (‰): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ε0 (‰): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel9, gridBagConstraints);

        txtE0.setEditable(false);
        txtE0.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtE0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtE0.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtE0, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("εu (‰): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jLabel10, gridBagConstraints);

        txtEu.setEditable(false);
        txtEu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtEu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEu.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(txtEu, gridBagConstraints);

        btnOK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOK.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(btnOK, gridBagConstraints);

        JTPane.addTab("Parâmetros obtidos", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("γ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtgamaEsforcos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtgamaEsforcos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgamaEsforcos.setText("1.4");
        txtgamaEsforcos.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel3.add(txtgamaEsforcos, gridBagConstraints);

        btnConfirmarGama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnConfirmarGama.setText("Confirmar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel3.add(btnConfirmarGama, gridBagConstraints);

        JTPane.addTab("Coeficiente de marjoração dos esforços", jPanel3);

        add(JTPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTPane;
    private javax.swing.JButton btnConfirmarGama;
    private javax.swing.JButton btnConfirmarGamas;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAlfa;
    private javax.swing.JTextField txtE0;
    private javax.swing.JTextField txtEu;
    private javax.swing.JTextField txtEuAco;
    private javax.swing.JTextField txtFcd;
    private javax.swing.JTextField txtLambda;
    private javax.swing.JTextField txtSigmaCd;
    private javax.swing.JTextField txtgamaC;
    private javax.swing.JTextField txtgamaEsforcos;
    private javax.swing.JTextField txtgamaF;
    // End of variables declaration//GEN-END:variables
}
