/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class LancaEsforcos extends javax.swing.JPanel {

    /**
     * Creates new form LancaEsforcos
     */
    public LancaEsforcos() {
        initComponents();
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(240, 220);
    }

    public JButton getBtnLancar() {
        return btnLancar;
    }

    public JPanel getJPanelE() {
        return JPanelE;
    }

    public JTextField getTxtMx() {
        return txtMx;
    }

    public JTextField getTxtMy() {
        return txtMy;
    }

    public JTextField getTxtNk() {
        return txtNK;
    }

    public JTextField getTxtEx() {
        return txtEx;
    }

    public JTextField getTxtEy() {
        return txtEy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanelE = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNK = new javax.swing.JTextField();
        btnLancar = new javax.swing.JButton();

        JPanelE.setBackground(new java.awt.Color(255, 255, 255));
        JPanelE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excêntricidades ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        JPanelE.setPreferredSize(new java.awt.Dimension(240, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("eX:");
        JPanelE.add(jLabel4);

        txtEx.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtEx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEx.setPreferredSize(new java.awt.Dimension(50, 20));
        JPanelE.add(txtEx);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("cm");
        JPanelE.add(jLabel6);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("eY:");
        JPanelE.add(jLabel5);

        txtEy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtEy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEy.setPreferredSize(new java.awt.Dimension(50, 20));
        JPanelE.add(txtEy);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("cm");
        JPanelE.add(jLabel7);

        setPreferredSize(new java.awt.Dimension(240, 220));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(65, 63, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Esforços solicitantes característicos");
        jPanel1.add(jLabel8);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(65, 63, 65));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Momento em X (kN.m):");
        jLabel1.setPreferredSize(new java.awt.Dimension(125, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        txtMx.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtMx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMx.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(txtMx, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Momento em Y (kN.m):");
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        txtMy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtMy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMy.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(txtMy, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Força Normal (kN):");
        jLabel3.setPreferredSize(new java.awt.Dimension(125, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtNK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtNK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNK.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(txtNK, gridBagConstraints);

        btnLancar.setBackground(new java.awt.Color(69, 73, 74));
        btnLancar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLancar.setText("Lançar esforços ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(btnLancar, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelE;
    private javax.swing.JButton btnLancar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtEx;
    private javax.swing.JTextField txtEy;
    private javax.swing.JTextField txtMx;
    private javax.swing.JTextField txtMy;
    private javax.swing.JTextField txtNK;
    // End of variables declaration//GEN-END:variables
}
