/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class verticesCoordenates extends javax.swing.JPanel {

    /**
     * Creates new form verticesCoordenates
     */
    public verticesCoordenates() {
        initComponents();
    }

    public JButton getBtnOk() {
        return btnOK;
    }

    public JTextField getTxtCX() {
        return txtCX;
    }
    public JTextField getTxtCY(){
    return txtTCY;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtCX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTCY = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(200, 100));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Coordenada X (cm): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(jLabel1, gridBagConstraints);

        txtCX.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtCX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCX.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(txtCX, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Coordenada Y (cm): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 6, 7);
        add(jLabel2, gridBagConstraints);

        txtTCY.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtTCY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTCY.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(txtTCY, gridBagConstraints);

        btnOK.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOK.setText("Lançar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnOK, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCX;
    private javax.swing.JTextField txtTCY;
    // End of variables declaration//GEN-END:variables
}
